schema_version: 1

context:
  name: gempy-engine
  version: "2026.0.3.post1"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gempy_engine-${{ version }}.tar.gz
  sha256: d4c708d5f4a9435bd4e7838d428294923f81eb163ef6cc8840fd19612536e430

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=${{ python_min }}
    - numpy
    - pydantic
    - python-dotenv >=1.0.1,<1.1.dev0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - gempy_engine
      pip_check: true

about:
  summary: A Python package necessary for GemPy.
  description: A Python package necessary for GemPy.
  license: EUPL-1.2
  license_file: LICENSE
  homepage: https://github.com/gempy-project/gempy_engine
  repository: https://github.com/gempy-project/gempy_engine

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
    - conda-forge/gempy
